### ISSUE TITLE
Error applying catalog

### ISSUE THREAD

**Issue by basher590** [voxpupuli/puppet-windows_autoupdate#4]
Hi,

I am getting an "uninitialized constant" error when i try to apply the WindowsAutoUpdate class. v0.0.2 

I have installed the dependencies, 
JoshCooper/PowerShell v0.0.6 
puppetlabs/registry v0.1.2 
puppetlabs/stdlib v3.2.0

I get the following error: 
Failed to apply catalog: Parameter path failed on Registry_key[HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU]: Munging failed for value "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" in class path: uninitialized constant PuppetX::Puppetlabs::Registry::KEY_WOW64_64KEY at /etc/puppetlabs/puppet/modules/windows_autoupdate/manifests/init.pp:32 Wrapped exception: Munging failed for value "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU" in class path: uninitialized constant PuppetX::Puppetlabs::Registry::KEY_WOW64_64KEY

Have I missed something?

**Comment by pavan2004** [comment]
I have just applied the windows_autoupdate class to my windows node in my PE 3.8 getting error as couldnot receive catalog from the remote server error 400 on server  validate _re 1 doesnot match ["^[0,1] $"]  at /etcx/puppetlabs/environments/production/modules/windows_autoupdate/manifests/init.pp:66 on windows node.

Please advise

**Comment by pavan2004** [comment]
OS on windows node is Windows 2012 x64 bit

**Comment by trekytech7** [comment]
Has there been a fix to this error? Progress? (puppet-windows_autoupdate v1.0.1)

Installed dependencies:
> puppetlabs-powershell v1.0.4
> puppetlabs/registry v1.1.2
> puppetlabs/stdlib v4.9.0

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
