### ISSUE TITLE
Deprecation of this module in favor of puppetlabs-wsus_client

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-windows_autoupdate#43]
Comparing this module to https://github.com/puppetlabs/puppetlabs-wsus_client it looks like we should deprecate this module.  The reasons are listed below:

**Why we should deprecate this**
1. wsus_client module is essentially a superset of this module in that it **contains all + more** of this module.
1. wsus_client module is puppet supported module and has some nice tests and support around it.

**Things to happen before the deprecation**
Before the deprecation happens though the wsus_client should have the following done:

- [X] Create a ticket in puppetlabs jira
- [ ] Update the documentation on the wsus_client module to indicate how a user without a wsus server can get the windows update agent to pull updates directly from "Microsoft Update".

**Source**
Below is the msdn documentation that states that setting UseWUServer to 0 will pull updates directly from Microsoft Update.
https://msdn.microsoft.com/en-us/library/dd939844(v=ws.10).aspx

**Comment by ekohl** [comment]
Do we have any docs/procedures on deprecating voxpupuli modules? IMHO we should have very clear indications on github and the forge.

**Comment by TraGicCode** [comment]
Not that i know of.  I'm sure @bastelfreak or @alexjfisher Can chime in on this.

**Comment by bastelfreak** [comment]
the IIS module is the only one that got deprecated. We only marked it as deprecated on the forge as far as I can remember. It should also be written down to the README.md on github.

**Comment by cjeffers** [comment]
So in order to use wsus_client for autoupdates from Microsoft, would the following suffice?
```
class { 'wsus_client':
  server_url => false,
}
```
I was considering that module for this purpose, but [the documentation says](https://github.com/puppetlabs/puppetlabs-wsus_client#server_url):

> If this parameter is set to 'false', Puppet sets UseWUServer to false, disabling WSUS updates on the client.

 And that scared me off, since I'm fine with the default Windows Update for my server.

**Comment by TraGicCode** [comment]
@cjeffers I need to dig into the code again and take a look.  One of the following will happen if i remember correctly.

1. Just documentation changes
1. A minor change to explicitly set the UseWUServer to 0 when no server_url is specific + documentation changes.

Either way the change is small.  Just need to get the ball rolling and make sure puppetlabs will accept the change.

**Comment by cjeffers** [comment]
@TraGicCode Awesome, thanks. I took a peek at the code, and it does look like it will set UseWUServer to 0 when server_url is set to false (assuming `bool2num` does the obvious thing). I will go ahead with that, then. I can open a PR for puppetlabs to change the docs.

**Comment by TraGicCode** [comment]
@cjeffers After looking at this further i think this might not be the best idea.  I have a couple of concerns that make me feel like this is a bad idea and without some thought and collaboration with the puppetlabs windows team i dont think this is a good idea.  Below are some concerns i have about this along with my thoughts.

1. The wsus_client module explicitly keeps calling out working with a wsus server that you have setup in your environment and want to connect a client to.

1. If we did update the documentation on how to get this to pull updates from microsoft it would cause for a confusing interface for users trying to use this module.  server_url => false is not intuitive.  

1. We could update the public interface ( parameters ) but then again the module name is still wsus_client.  I'm not even sure if this still makes sense anymore if being able to pull from Microsoft.

I'll leave this open and hopefully this gets triaged and examined by the puppetlabs windows team soon.

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
